language: groovy

jdk:
  - openjdk7
  - oraclejdk8

script:
  - ./gradlew clean check uploadArchives --full-stacktrace
  - cd samples/jacoco; ./gradlew clean check --full-stacktrace; cd ../../
  - cd samples/cobertura; ./gradlew clean check --full-stacktrace; cd ../../

after_success:
  - ./gradlew cobertura coveralls --full-stacktrace
